### ISSUE TITLE
Dependabot can't access secrets and fails pull request tests

### ISSUE THREAD

**Issue by ofersadan85** [ohad24/encyclo-flower#16]
This error prevents any tests from Dependabot to pass (Dependabot can't access secrets)
I can try to fix this by splitting Dependabot workflows from the others (Will improve CI)
let me know if you want me to work on this

The error in Dependabot PR:
```
Error: google-github-actions/auth failed with: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.
```

**Comment by ohad24** [comment]
https://docs.pytest.org/en/latest/how-to/skipping.html#id1
maybe

**Comment by ofersadan85** [comment]
It would work for the tests themselves, but not for the fact that the current workflows tries to access secrets (it fails before pytest even starts)
