### ISSUE TITLE
API should fail gracefully

### ISSUE THREAD

**Issue by ofersadan85** [ohad24/encyclo-flower#18]
API should fail gracefully in any of these conditions:

- MONGO_URI is not set or the connection fails
- GOOGLE_APPLICATION_CREDENTIALS is not set or the file doesn't exist or the storage itself isn't available

To fail gracefully is to continue working but to return error messages as replies to API calls

We've discussed it a lot, the issue with google storage is already being worked on in #17 in tests (but should also not be an issue in a working API instance without tests).

I suggest to keep this issue open to track this and as a reminder, but it's **not urgent** 

This is for several reasons that aren't related to dependabot as in #16 or pytest in #17 :

- Docker image creation fails without a clear error indicating what the problem is, hard to debug
- Test/dev environments are more difficult to setup quickly (even if unrelated to running tests)
- At the very minimum, a "hello world" function that doesn't require extra resources shouldn't fail when un-needed resources aren't available, this will be easier to scale-up in the future (if the API is split between servers with different resources, for example)

**Comment by ohad24** [comment]
So you suggest to check those two environment variables before application finish to init, and if they (at least one) don't contains a value, the application will return return a non zero code. right ?

**Comment by ohad24** [comment]
I think this is OK,
The application will fail per the requested route and not on the general startup
I added and health check router https://github.com/ohad24/encyclo-flower/commit/c46e90136f28a47214c5c15bab800cfa2054603f
