### ISSUE TITLE
Suggested fix: minimize packages in requirements.txt

### ISSUE THREAD

**Issue by ofersadan85** [ohad24/encyclo-flower#21]
The reason why we have so many package conflicts (as shown by dependabot pull requests) is beacuse the `requirements.txt` is too specific about packages we don't care about (because of `pip freeze`)

`src/api/requirements.txt` should only contain packages that we explicitly need for the api and `pip` should resolve the dependencies automatically. We will receive less dependabot pull requests and all of them will be 100% relevant. Another advantage is that no "dev" packages (`black` for example) are needed for the api docker image. If we need "dev" packages, they should be in another `requirements.txt` in the root of the repository

If it seems ok to you I suggest I will minimize `src/api/requirements.txt` as much as possible (the minimal version that passes all tests)

**Comment by ohad24** [comment]
> The reason why we have so many package conflicts (as shown by dependabot pull requests) is beacuse the `requirements.txt` is too specific about packages we don't care about (because of `pip freeze`)
> 
> `src/api/requirements.txt` should only contain packages that we explicitly need for the api and `pip` should resolve the dependencies automatically. We will receive less dependabot pull requests and all of them will be 100% relevant. Another advantage is that no "dev" packages (`black` for example) are needed for the api docker image. If we need "dev" packages, they should be in another `requirements.txt` in the root of the repository
> 
> If it seems ok to you I suggest I will minimize `src/api/requirements.txt` as much as possible (the minimal version that passes all tests)

Yes, that is exactly what I thought of but didn't have the time to verify this.
Please minimize the `src/api/requirements.txt` and create new one for easy development.
When you find a time.
Thanks!
