### ISSUE TITLE
Make server/docker-compose.yml ready for main domain

### ISSUE THREAD

**Issue by ohad24** [ohad24/encyclo-flower#34]
Done in https://github.com/ohad24/encyclo-flower/pull/32/commits/fbdc3a0ce1df4b8dde80aaa0b8b72f930f5dfea9 But i still recommend to open an issue about it later

_Originally posted by @ofersadan85 in https://github.com/ohad24/encyclo-flower/pull/32#discussion_r835733157_

**Comment by ofersadan85** [comment]
Can you specify what images should be on both the dev and production stacks? Is the website staying? The API and what else?
