### ISSUE TITLE
Our swag gateway doesn't have a dev version

### ISSUE THREAD

**Issue by ohad24** [ohad24/encyclo-flower#55]
Our swag gateway doesn't have a dev version so this is temporary, latest tag will be applied soon after some testing

_Originally posted by @ofersadan85 in https://github.com/ohad24/encyclo-flower/pull/53#discussion_r843189685_

**Comment by ohad24** [comment]
@ofersadan85 
So what we need to configure to address this issue ?

**Comment by ofersadan85** [comment]
But still this is our gateway so only one version can be live unless you want the other one to run on other ports (8080 for http and 8443 for https for example)

**Comment by ohad24** [comment]
> But still this is our gateway so only one version can be live unless you want the other one to run on other ports (8080 for http and 8443 for https for example)

Currently we have access to dev API VIA the `dev` subdomain, no ?

**Comment by ofersadan85** [comment]
Each subdomain has different images but all subdomains run through one swag proxy

We have 2x API instances and we'll have 2x FE instances but only 1x swag. If you want more the options are:

1. Access through a different port
2. Assign a second external IP to the vm
3. Create another vm

**Comment by ofersadan85** [comment]
Switch to latest version in bd9f4cfadee8cbe2f1ae7e6e37d8816005637324

**Comment by ohad24** [comment]
This is the problem https://github.com/ohad24/encyclo-flower/runs/6142171221?check_suite_focus=true#step:3:28 ?
After merge some branch

**Comment by ohad24** [comment]
> This is the problem https://github.com/ohad24/encyclo-flower/runs/6142171221?check_suite_focus=true#step:3:28 ? After merge some branch

I'll open new issue for the test/dev api deployment

No need to run the swag dev version.
