### ISSUE TITLE
Depandabot tried to push and faild 

### ISSUE THREAD

**Issue by ohad24** [ohad24/encyclo-flower#56]
https://github.com/ohad24/encyclo-flower/runs/5855649580?check_suite_focus=true#step:4:7

Maybe because I let him (the bot) to merge (using `@dependabot merge`) ?

@ofersadan85, please advise.

Thanks

**Comment by ofersadan85** [comment]
I just re run the same job and it passed ok, I'm guessing temporary login issue of DockerHub and not us

https://github.com/ohad24/encyclo-flower/actions/runs/2104068154

**Comment by ohad24** [comment]
> I just re run the same job and it passed ok, I'm guessing temporary login issue of DockerHub and not us
> 
> https://github.com/ohad24/encyclo-flower/actions/runs/2104068154

OK, I'll not use the `@dependabot merge` command. Thanks

**Comment by ofersadan85** [comment]
> > I just re run the same job and it passed ok, I'm guessing temporary login issue of DockerHub and not us
> > https://github.com/ohad24/encyclo-flower/actions/runs/2104068154
> 
> OK, I'll not use the `@dependabot merge` command. Thanks

I think you can, I really don't think that was the problem
